theme: jekyll-theme-chirpy

lang: de
timezone: Europe/Berlin

title: Modern Workplace Diaries Blog
tagline: Gedanken, Guides und Erfahrungen rund um Modern Work.
description: Modern Workplace Diaries Blog mit Praxiserfahrungen zu Microsoft 365, Security, AI und produktivem Arbeiten.

url: "https://tstrueber.github.io"
baseurl: "/blog01"

github:
  username: tstrueber

social:
  name: Timo
  email: ""
  links: []

avatar: "/assets/img/site/profilbild-timo.jpg"

toc: true

paginate: 10

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      toc: true
  - scope:
      path: "_tabs"
    values:
      layout: page
      permalink: /:title/
