theme: jekyll-theme-chirpy

lang: de
timezone: Europe/Berlin

title: Timos Blog
tagline: Notizen, Ideen und Projekte.
description: Notizen, Ideen und Projekte.

url: "https://tstrueber.github.io"
baseurl: "/blog01"

github:
  username: tstrueber

social:
  name: Timo
  email: ""
  links: []

avatar: ""

toc: true

paginate: 10

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      toc: true
  - scope:
      path: "_tabs"
    values:
      layout: page
      permalink: /:title/
